/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.DonorRole;

import Business.Donor.Donor;
import Business.Organization.Organization;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonorRegistrationRequest;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ButtonGroup;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
/**
 *
 * @author wanyuchiu
 */
public class DonorRegistrationJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    /**
     * Creates new form DonorRegistrationJPanel
     */
    public DonorRegistrationJPanel(JPanel userProcessContainer, UserAccount account, Organization org, Enterprise ent) {
        
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = org;
        this.enterprise = ent;
        
         // 初始化數據
        populateComboBoxes();
        setupRadioButtonGroups();  
    }
    
     private void populateComboBoxes() {
        // 填充性別選項
        genderJComboBox.removeAllItems();
        genderJComboBox.addItem("Male");
        genderJComboBox.addItem("Female");
        genderJComboBox.addItem("Other");
        
        // 填充血型選項
        ComboBoxBloodType.removeAllItems();
        ComboBoxBloodType.addItem("A+");
        ComboBoxBloodType.addItem("A-");
        ComboBoxBloodType.addItem("B+");
        ComboBoxBloodType.addItem("B-");
        ComboBoxBloodType.addItem("AB+");
        ComboBoxBloodType.addItem("AB-");
        ComboBoxBloodType.addItem("O+");
        ComboBoxBloodType.addItem("O-");
        
        // 填充器官類型選項
        txtOrganType.removeAllItems();
        txtOrganType.addItem("Heart");
        txtOrganType.addItem("Liver");
        txtOrganType.addItem("Kidney");
        txtOrganType.addItem("Lung");
        txtOrganType.addItem("Pancreas");
        txtOrganType.addItem("Cornea");
        
        // 填充州選項
        ComboBoxStates.removeAllItems();
        String[] states = {"AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
                          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
                          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
                          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
                          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"};
        for (String state : states) {
            ComboBoxStates.addItem(state);
        }
    }
    
    private void setupRadioButtonGroups() {
        // 為每組問題創建 ButtonGroup
        ButtonGroup group1 = new ButtonGroup();
        group1.add(btnYesQ1);
        group1.add(btnNoQ1);
        
        ButtonGroup group2 = new ButtonGroup();
        group2.add(btnYesQ2);
        group2.add(btnNoQ2);
        
        ButtonGroup group3 = new ButtonGroup();
        group3.add(btnYesQ4);
        group3.add(btnNoQ3);
    }
    
    /**
     * Calculate age from date of birth
     */
    private int calculateAge(Date dateOfBirth) {
        Calendar dob = Calendar.getInstance();
        dob.setTime(dateOfBirth);
        Calendar today = Calendar.getInstance();
    
        int age = today.get(Calendar.YEAR) - dob.get(Calendar.YEAR);
    
        // Adjust if birthday hasn't occurred yet this year
        if (today.get(Calendar.DAY_OF_YEAR) < dob.get(Calendar.DAY_OF_YEAR)) {
            age--;
        }
    
        return age;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnYesQ2 = new javax.swing.JRadioButton();
        btnYesQ1 = new javax.swing.JRadioButton();
        btnYesQ4 = new javax.swing.JRadioButton();
        genderJComboBox = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        txtPIN = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        ComboBoxStates = new javax.swing.JComboBox<>();
        ComboBoxBloodType = new javax.swing.JComboBox<>();
        txtEmails = new javax.swing.JTextField();
        txtStreetAddress = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtOrganType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnNoQ2 = new javax.swing.JRadioButton();
        btnNoQ1 = new javax.swing.JRadioButton();
        btnNoQ3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel7.setText("Age:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setText("Gender:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel9.setText("Blood Type:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel12.setText("Street address:");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel13.setText("City:");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel14.setText("States:");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel15.setText("ZipCode:");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel16.setText("Phone Number:");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel17.setText("Email:");

        jLabel19.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel19.setText("Do you have any chronic conditions?");

        jLabel20.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel20.setText("Are you currently feeling unwell?");

        jLabel22.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel22.setText("Do you have any contagious diseases?");

        btnYesQ2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnYesQ2.setText("Yes");

        btnYesQ1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnYesQ1.setText("Yes");

        btnYesQ4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnYesQ4.setText("Yes");

        genderJComboBox.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        genderJComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        genderJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderJComboBoxActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel23.setText("Address Details");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel24.setText("Elibility Requirements:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel10.setText("PIN:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel11.setText("Organ Type:");

        txtAge.setEditable(false);
        txtAge.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setText("Donor Aplication:");

        btnSubmit.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnNoQ2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNoQ2.setText("No");

        btnNoQ1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNoQ1.setText("No");
        btnNoQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoQ1ActionPerformed(evt);
            }
        });

        btnNoQ3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNoQ3.setText("No");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setText("DOB:");

        txtDOB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDOBFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(430, 430, 430))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(33, 33, 33)
                                .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(36, 36, 36)
                                        .addComponent(btnYesQ1))
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(330, 330, 330)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnYesQ2)
                                                .addGap(43, 43, 43)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnNoQ1)
                                                    .addComponent(btnNoQ2)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnYesQ4)
                                                .addGap(45, 45, 45)
                                                .addComponent(btnNoQ3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(50, 50, 50)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(genderJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmails, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(112, 112, 112)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel16))
                                                .addGap(32, 32, 32)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtOrganType, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ComboBoxBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(35, 35, 35)
                                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ComboBoxStates, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(510, 510, 510)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 50, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtEmails, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(genderJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOrganType, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(btnYesQ1))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnYesQ2)
                                            .addComponent(btnNoQ2)))
                                    .addComponent(btnNoQ1))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNoQ3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(btnYesQ4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel20)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(ComboBoxStates, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(349, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 78, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void genderJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderJComboBoxActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
         try {
            // 驗證所有欄位
            if (!validateInput()) {
                return;
            }
            
            // 檢查健康資格（所有問題都必須選 No）
            if (!checkEligibility()) {
                JOptionPane.showMessageDialog(this, 
                    "❌ Registration Failed!\n\n" +
                    "You are not eligible to donate.\n" +
                    "All health screening questions must be answered 'No'.", 
                    "Eligibility Failed", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // 創建 Donor 並保存資料
            Donor donor = new Donor(txtName.getText().trim());
            donor.setEmail(txtEmails.getText().trim());
            donor.setContactNumber(txtPhoneNumber.getText().trim());
            
            // 解析並設置出生日期
            Date dob = parseDateOfBirth(txtDOB.getText().trim());
            if (dob != null) {
                donor.setDateOfBirth(dob);
            }
            
            donor.setBloodType((String) ComboBoxBloodType.getSelectedItem());
            donor.setOrganToDonate((String) txtOrganType.getSelectedItem());
            donor.setMedicalHistory(buildMedicalHistory());
            donor.setStatus("Pending Hospital Review");
            
            // 保存到系統
            organization.getDonorDirectory().addDonor(donor);
            
            // ============ 创建 WorkRequest 并添加到 WorkQueue ============

            // 创建 DonorRegistrationRequest
           DonorRegistrationRequest request = new DonorRegistrationRequest();
           request.setDonor(donor);
           request.setSender(userAccount);
           request.setStatus("Pending Hospital Review");
           request.setRequestDate(new Date());
           request.setMessage("Donor registration request from " + donor.getName());

           // 添加到 WorkQueue
           organization.getWorkQueue().addWorkRequest(request);
           // ============ 调试信息 ============
System.out.println("=== DONOR SUBMISSION DEBUG ===");
System.out.println("Donor Organization: " + organization.getName());
System.out.println("Organization ID: " + organization.getOrganizationID());
System.out.println("Request ID: " + request.getRequestID());
System.out.println("Donor Name: " + request.getDonorName());
System.out.println("WorkQueue Size: " + organization.getWorkQueue().getWorkRequestList().size());
System.out.println("=============================");
// ============ End ============
            
            // 顯示成功訊息
            JOptionPane.showMessageDialog(this, 
                "✅ Registration Successful!\n\n" +
                "Donor ID: " + donor.getDonorId() + "\n" +
                "Name: " + donor.getName() + "\n" +
                "Age: " + txtAge.getText() + " years old\n" +
                "Blood Type: " + donor.getBloodType() + "\n" +
                "Organ: " + donor.getOrganToDonate() + "\n\n" +
                "Status: Pending Hospital Review\n\n" +
                "Your application will be reviewed by a Hospital Officer.", 
                "Registration Success", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // 清空表單
            clearForm();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "❌ Error: " + e.getMessage(), 
                "System Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
                                             
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int response = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to cancel?\n" +
            "All entered information will be lost.",
            "Confirm Cancel",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
        if (response == JOptionPane.YES_OPTION) {
            clearForm();
            userProcessContainer.remove(this);
            userProcessContainer.repaint();
            userProcessContainer.revalidate();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
     // ========== 輔助方法 ==========
    
    /**
     * 解析出生日期字符串 (格式: YYYY-MM-DD)
     */
    private Date parseDateOfBirth(String dobStr) {
        if (dobStr == null || dobStr.trim().isEmpty()) {
            return null;
        }
        
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            sdf.setLenient(false); // 嚴格驗證日期
            return sdf.parse(dobStr.trim());
        } catch (ParseException e) {
            return null;
        }
    }
    
    /**
     * 驗證所有必填欄位
     */
    private boolean validateInput() {
        // 驗證姓名
        if (txtName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your name!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        // 验证姓名不能包含数字
        if (containsDigit(txtName.getText().trim())) {
           JOptionPane.showMessageDialog(this, 
        "Name cannot contain numbers!", 
        "Validation Error", 
        JOptionPane.WARNING_MESSAGE);
           return false;
        }
        
        // Validate DOB format and value
        if (txtDOB.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your date of birth!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    
        Date dobDate = null;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
            sdf.setLenient(false);
            dobDate = sdf.parse(txtDOB.getText().trim());
        
            // Check if date is in the future
            if (dobDate.after(new Date())) {
                JOptionPane.showMessageDialog(this, "Date of birth cannot be in the future!", 
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format! Please use MM/DD/YYYY", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    
        // Validate age (auto-calculated from DOB)
        if (txtAge.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a valid date of birth to calculate age!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    
        try {
            int age = Integer.parseInt(txtAge.getText().trim());
            if (age < 18 || age > 75) {
                JOptionPane.showMessageDialog(this, 
                    "Donors must be between 18 and 75 years old!", 
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Invalid age value!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    
        // 驗證 Email
        if (txtEmails.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if (!txtEmails.getText().trim().contains("@")) {
            JOptionPane.showMessageDialog(this, 
                "Please enter a valid email address!", 
                "Validation Error", 
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        // Validate phone number - must be exactly 10 digits
        if (txtPhoneNumber.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your phone number!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    
        String phoneDigits = txtPhoneNumber.getText().trim().replaceAll("[^0-9]", "");
        if (phoneDigits.length() != 10) {
            JOptionPane.showMessageDialog(this, "Phone number must be exactly 10 digits!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        // 驗證 PIN
        if (txtPIN.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your PIN!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        // 驗證血型
        if (ComboBoxBloodType.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select your blood type!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        // 驗證器官類型
        if (txtOrganType.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select organ type!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        // 驗證地址
        if (txtStreetAddress.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your street address!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        // 验证地址不能全是数字
        if (isAllDigits(txtStreetAddress.getText().trim())) {
           JOptionPane.showMessageDialog(this, 
        "Street address cannot be only numbers!", 
        "Validation Error", 
        JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if (txtCity.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your city!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        // 验证城市名不能包含数字
        if (containsDigit(txtCity.getText().trim())) {
            JOptionPane.showMessageDialog(this, 
        "City name cannot contain numbers!", 
        "Validation Error", 
        JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if (txtZipCode.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your zip code!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        // Validate zip code - must be exactly 5 digits
        if (txtZipCode.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your zip code!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    
        String zipDigits = txtZipCode.getText().trim().replaceAll("[^0-9]", "");
        if (zipDigits.length() != 5) {
            JOptionPane.showMessageDialog(this, "Zip code must be exactly 5 digits!", 
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        // 驗證健康問題
        if (!btnYesQ1.isSelected() && !btnNoQ1.isSelected()) {
            JOptionPane.showMessageDialog(this, 
                "Please answer: Do you have any chronic conditions?", 
                "Health Screening Required", 
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if (!btnYesQ2.isSelected() && !btnNoQ2.isSelected()) {
            JOptionPane.showMessageDialog(this, 
                "Please answer: Are you currently feeling unwell?", 
                "Health Screening Required", 
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if (!btnYesQ4.isSelected() && !btnNoQ3.isSelected()) {
            JOptionPane.showMessageDialog(this, 
                "Please answer: Do you have any contagious diseases?", 
                "Health Screening Required", 
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    /**
     * 檢查健康資格 - 所有問題都必須回答 No
     */
    private boolean checkEligibility() {
        // 如果任何一個問題回答 Yes，則不符合捐贈資格
        if (btnYesQ1.isSelected() || btnYesQ2.isSelected() || btnYesQ4.isSelected()) {
            return false;
        }
        return true;
    }
    
    /**
     * 構建醫療歷史記錄
     */
    private String buildMedicalHistory() {
        StringBuilder history = new StringBuilder();
        history.append("=== DONOR REGISTRATION ===\n\n");
        history.append("Date of Birth: ").append(txtDOB.getText().trim()).append("\n");
        history.append("Address: ").append(txtStreetAddress.getText().trim())
               .append(", ").append(txtCity.getText().trim())
               .append(", ").append((String) ComboBoxStates.getSelectedItem())
               .append(" ").append(txtZipCode.getText().trim()).append("\n");
        history.append("PIN: ").append(txtPIN.getText().trim()).append("\n");
        history.append("Gender: ").append((String) genderJComboBox.getSelectedItem()).append("\n");
        history.append("Age: ").append(txtAge.getText().trim()).append("\n\n");
        history.append("Health Screening:\n");
        history.append("  Chronic conditions: ").append(btnYesQ1.isSelected() ? "Yes" : "No").append("\n");
        history.append("  Currently unwell: ").append(btnYesQ2.isSelected() ? "Yes" : "No").append("\n");
        history.append("  Contagious diseases: ").append(btnYesQ4.isSelected() ? "Yes" : "No").append("\n");
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        history.append("\nRegistered: ").append(sdf.format(new Date()));
        return history.toString();
    }
    
    /**
     * 清空表單所有欄位
     */
    private void clearForm() {
        txtName.setText("");
        txtAge.setText("");
        txtDOB.setText("");
        txtEmails.setText("");
        txtPhoneNumber.setText("");
        txtPIN.setText("");
        txtStreetAddress.setText("");
        txtCity.setText("");
        txtZipCode.setText("");
        
        if (genderJComboBox.getItemCount() > 0) {
            genderJComboBox.setSelectedIndex(0);
        }
        if (ComboBoxBloodType.getItemCount() > 0) {
            ComboBoxBloodType.setSelectedIndex(0);
        }
        if (txtOrganType.getItemCount() > 0) {
            txtOrganType.setSelectedIndex(0);
        }
        if (ComboBoxStates.getItemCount() > 0) {
            ComboBoxStates.setSelectedIndex(0);
        }
        
        btnYesQ1.setSelected(false);
        btnNoQ1.setSelected(false);
        btnYesQ2.setSelected(false);
        btnNoQ2.setSelected(false);
        btnYesQ4.setSelected(false);
        btnNoQ3.setSelected(false);
    }
    
    /**
 * 检查字符串是否包含数字
 */
    private boolean containsDigit(String str) {
        for (char c : str.toCharArray()) {
           if (Character.isDigit(c)) {
              return true;
        }
      }
        return false;
    }

/**
 * 检查字符串是否全是数字
 */
    private boolean isAllDigits(String str) {
        if (str == null || str.isEmpty()) {
          return false;
    }
    for (char c : str.toCharArray()) {
        if (!Character.isDigit(c) && c != ' ') {  // 允许空格
            return false;
        }
      }
    return true;
    }

    private void btnNoQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoQ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoQ1ActionPerformed

    private void txtDOBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOBFocusLost
        // TODO add your handling code here:
        // Auto-calculate age when user finishes entering DOB
        String dobText = txtDOB.getText().trim();
        if (!dobText.isEmpty()) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
                sdf.setLenient(false);
                Date dob = sdf.parse(dobText);
                int age = calculateAge(dob);
                if (age >= 0 && age <= 120) {
                    txtAge.setText(String.valueOf(age));
                } else {
                    txtAge.setText("");
                }
            } catch (ParseException e) {
                txtAge.setText("");
            }
        } else {
            txtAge.setText("");
        }
    }//GEN-LAST:event_txtDOBFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxBloodType;
    private javax.swing.JComboBox<String> ComboBoxStates;
    private javax.swing.JRadioButton btnNoQ1;
    private javax.swing.JRadioButton btnNoQ2;
    private javax.swing.JRadioButton btnNoQ3;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JRadioButton btnYesQ1;
    private javax.swing.JRadioButton btnYesQ2;
    private javax.swing.JRadioButton btnYesQ4;
    private javax.swing.JComboBox genderJComboBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmails;
    private javax.swing.JTextField txtName;
    private javax.swing.JComboBox<String> txtOrganType;
    private javax.swing.JTextField txtPIN;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
