package userinterface.LabRoleWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Donor.Donor;
import Business.Recipient.Recipient;
import Business.Medical.MedicalTestResult;
import Business.Organization.DonorOrganization;
import Business.Organization.RecipientOrganization;
import Business.Organization.DoctorOrganization;
import Business.WorkQueue.MedicalTestWorkRequest;
import Business.WorkQueue.WorkRequest; // Required for iterating work queue
import java.awt.CardLayout;
import java.util.Date;
import java.util.ArrayList; // Restore ArrayList as it was needed before.
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class LabTechnicianWorkAreaJPanel extends JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private Network network;

    /**
     * Creates new form LabTechnicianWorkAreaJPanel
     */
    public LabTechnicianWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        
        lblEnterpriseValue.setText(enterprise.getName());
        populateSubjectsTable();
    }
    
    private void populateSubjectsTable() {
        DefaultTableModel model = (DefaultTableModel) tblSubjects.getModel();
        model.setRowCount(0);
        
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof MedicalTestWorkRequest) {
                MedicalTestWorkRequest mRequest = (MedicalTestWorkRequest) request;
                // Only show requests assigned to this lab technician and in "Pending Lab Tests" status
                if (mRequest.getReceiver() == userAccount && mRequest.getStatus().equalsIgnoreCase("Pending Lab Tests")) {
                    Object[] row = new Object[6];
                    String subjectName = "";
                    String subjectType = "";
                    String organ = "";
                    String bloodType = "";

                    if (mRequest.getDonor() != null && mRequest.getRecipient() != null) {
                        subjectName = mRequest.getDonor().getName() + " (D) / " + mRequest.getRecipient().getName() + " (R)";
                        subjectType = "Match";
                        organ = mRequest.getDonor().getOrganToDonate(); // Or mRequest.getRecipient().getOrganNeeded()
                        bloodType = mRequest.getDonor().getBloodType(); // Assuming compatible blood types for a match
                    } else if (mRequest.getDonor() != null) {
                        subjectName = mRequest.getDonor().getName();
                        subjectType = "Donor";
                        organ = mRequest.getDonor().getOrganToDonate();
                        bloodType = mRequest.getDonor().getBloodType();
                    } else if (mRequest.getRecipient() != null) {
                        subjectName = mRequest.getRecipient().getName();
                        subjectType = "Recipient";
                        organ = mRequest.getRecipient().getOrganNeeded();
                        bloodType = mRequest.getRecipient().getBloodType();
                    }
                    
                    row[0] = subjectName;
                    row[1] = subjectType;
                    row[2] = organ;
                    row[3] = bloodType;
                    row[4] = mRequest.getStatus();
                    row[5] = mRequest; // The request object itself
                    model.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        lblEnterpriseValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubjects = new javax.swing.JTable();
        btnUploadResults = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Lab Technician Work Area");

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnterprise.setText("Enterprise:");

        lblEnterpriseValue.setText("<value>");

        tblSubjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Subject Name", "Type", "Organ", "Blood Type", "Status", "Request"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSubjects);

        btnUploadResults.setText("Upload Test Results");
        btnUploadResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadResultsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Subjects Requiring Tests:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblEnterprise)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblEnterpriseValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnUploadResults, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterprise)
                    .addComponent(lblEnterpriseValue))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUploadResults)
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void btnUploadResultsActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int selectedRow = tblSubjects.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Medical Test Request.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        MedicalTestWorkRequest request = (MedicalTestWorkRequest) tblSubjects.getValueAt(selectedRow, 5); // MedicalTestWorkRequest object is at index 5

        if (request.getStatus().equalsIgnoreCase("Tests Uploaded, Pending Doctor Verification")) {
            JOptionPane.showMessageDialog(this, "Test results for this request have already been uploaded.", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        String testName = JOptionPane.showInputDialog(this, "Enter Test Name:", request.getTestType()); // Pre-fill with existing test type
        if (testName == null || testName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Test Name cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String resultDetails = JOptionPane.showInputDialog(this, "Enter Result Details:");
        if (resultDetails == null || resultDetails.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Result Details cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Update the MedicalTestWorkRequest with results
        request.setTestType(testName);
        request.setTestResult(resultDetails);
        request.setRequestDate(new Date()); // Update request date or use resolve date for lab
        request.setStatus("Tests Uploaded, Pending Doctor Verification");

        // Find a Doctor Organization to send the request to
        Organization orgToReceive = null;
        UserAccount doctorAccount = null; // Declare here so it's accessible
        for (Network net : system.getNetworkList()) {
            for (Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                    if (org instanceof DoctorOrganization) {
                        orgToReceive = org;
                        if (!org.getUserAccountDirectory().getUserAccountList().isEmpty()) {
                            doctorAccount = org.getUserAccountDirectory().getUserAccountList().get(0); // Assign to the first doctor found
                            break; // Found a doctor, break inner loop
                        }
                    }
                }
                if (orgToReceive != null && doctorAccount != null) break; // Found org and doctor, break middle loop
            }
            if (orgToReceive != null && doctorAccount != null) break; // Found org and doctor, break outer loop
        }
        
        if (doctorAccount == null || orgToReceive == null) { // Check for both doctor and organization
            JOptionPane.showMessageDialog(this, "No Doctor User Accounts or Doctor Organization found to send the request to.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        request.setReceiver(doctorAccount); // Assign to the specific doctor user account
        
        // Add to work queue of Lab Technician's organization (current organization)
        organization.getWorkQueue().getWorkRequestList().add(request);
        
        // Add to work queue of the Doctor Organization
        orgToReceive.getWorkQueue().getWorkRequestList().add(request);

        // Update Donor/Recipient status based on the request's new status
        if (request.getDonor() != null) {
            request.getDonor().setStatus("Tests Uploaded, Pending Doctor Verification");
        } else if (request.getRecipient() != null) {
            request.getRecipient().setStatus("Tests Uploaded, Pending Doctor Verification");
        }
        
        JOptionPane.showMessageDialog(this, "Test results uploaded and sent for doctor verification.", "Upload Success", JOptionPane.INFORMATION_MESSAGE);
        populateSubjectsTable(); // Refresh table
    }                                                


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnUploadResults;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblEnterpriseValue;
    private javax.swing.JTable tblSubjects;
    // End of variables declaration                   
}
