package userinterface.LabRoleWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Donor.Donor;
import Business.Recipient.Recipient;
import Business.Medical.MedicalTestResult;
import Business.Organization.DonorOrganization;
import Business.Organization.RecipientOrganization;
import Business.Organization.DoctorOrganization;
import Business.WorkQueue.MedicalTestWorkRequest;
import Business.WorkQueue.WorkRequest; // Required for iterating work queue
import java.awt.CardLayout;
import java.util.Date;
import java.util.ArrayList; // Restore ArrayList as it was needed before.
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class LabTechnicianWorkAreaJPanel extends JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private Network network;

    /**
     * Creates new form LabTechnicianWorkAreaJPanel
     */
    public LabTechnicianWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        
        lblEnterpriseValue.setText(enterprise.getName());
        populateSubjectsTable();
    }
    
    private void populateSubjectsTable() {
        DefaultTableModel model = (DefaultTableModel) tblSubjects.getModel();
        model.setRowCount(0);
        
        // Populate Donors for initial testing
        for (Network net : system.getNetworkList()) {
            for (Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                    if (org instanceof DonorOrganization) {
                        DonorOrganization donorOrg = (DonorOrganization) org;
                        for (Donor donor : donorOrg.getDonorDirectory().getDonorList()) {
                            // Show if approved by hospital or needing retest (internal retest by lab)
                            if (donor.getStatus().equalsIgnoreCase("Approved by Hospital") || donor.getStatus().equalsIgnoreCase("Retest Required") || donor.getStatus().equalsIgnoreCase("Tests Verified")) {
                                Object[] row = new Object[5];
                                row[0] = donor; // The Donor object
                                row[1] = "Donor";
                                row[2] = donor.getOrganToDonate();
                                row[3] = donor.getBloodType();
                                row[4] = donor.getStatus();
                                model.addRow(row);
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        lblEnterpriseValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubjects = new javax.swing.JTable();
        btnUploadResults = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        
        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Lab Technician Work Area");
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.insets = new java.awt.Insets(10, 10, 20, 10);
        add(jLabel1, gbc);

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnterprise.setText("Enterprise:");
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        add(lblEnterprise, gbc);

        lblEnterpriseValue.setText("<value>");
        gbc.gridx = 1;
        add(lblEnterpriseValue, gbc);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Subjects Requiring Tests:");
        gbc.gridy = 2;
        gbc.gridx = 0;
        gbc.gridwidth = 2;
        gbc.insets = new java.awt.Insets(20, 10, 5, 10);
        add(jLabel2, gbc);
        
        tblSubjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Type", "Organ", "Blood Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSubjects);
        
        gbc.gridy = 3;
        gbc.fill = java.awt.GridBagConstraints.BOTH;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        add(jScrollPane1, gbc);

        btnUploadResults.setText("Upload Test Results");
        btnUploadResults.setBackground(new java.awt.Color(0, 120, 102));
        btnUploadResults.setForeground(java.awt.Color.WHITE);
        btnUploadResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadResultsActionPerformed(evt);
            }
        });
        gbc.gridy = 4;
        gbc.fill = java.awt.GridBagConstraints.NONE;
        gbc.weighty = 0;
        add(btnUploadResults, gbc);
    }// </editor-fold>                        

    private void btnUploadResultsActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int selectedRow = tblSubjects.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Donor or Recipient.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Object selectedSubject = tblSubjects.getValueAt(selectedRow, 0); // Must be Donor or Recipient

        String testName = JOptionPane.showInputDialog(this, "Enter Test Name:");
        if (testName == null || testName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Test Name cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String resultDetails = JOptionPane.showInputDialog(this, "Enter Result Details:");
        if (resultDetails == null || resultDetails.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Result Details cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (selectedSubject instanceof Donor) {
            Donor donor = (Donor) selectedSubject;
            // Update Donor status
            donor.setStatus("Tests Verified"); 
            // In a real system, MedicalTestResult might be added to a list within Donor
        } else { // Should only be Donor due to populateSubjectsTable filtering
             JOptionPane.showMessageDialog(this, "Invalid subject type selected. Only Donors can be processed.", "Error", JOptionPane.ERROR_MESSAGE);
             return;
        }
        
        JOptionPane.showMessageDialog(this, "Test results uploaded and status updated to 'Tests Completed - Lab Verified'.", "Upload Success", JOptionPane.INFORMATION_MESSAGE);
        populateSubjectsTable(); // Refresh table
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnUploadResults;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblEnterpriseValue;
    private javax.swing.JTable tblSubjects;
    // End of variables declaration                   
}
