package userinterface.LabRoleWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Donor.Donor;
import Business.Recipient.Recipient;
import Business.Medical.MedicalTestResult;
import Business.Organization.DonorOrganization;
import Business.Organization.RecipientOrganization;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class LabTechnicianWorkAreaJPanel extends JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private Network network;

    /**
     * Creates new form LabTechnicianWorkAreaJPanel
     */
    public LabTechnicianWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        
        lblEnterpriseValue.setText(enterprise.getName());
        populateSubjectsTable();
    }
    
    private void populateSubjectsTable() {
        DefaultTableModel model = (DefaultTableModel) tblSubjects.getModel();
        model.setRowCount(0);
        
        // This panel needs to show Donors/Recipients that require tests.
        // For simplicity, let's show all Donors/Recipients that are 'Registered', 'Approved by Hospital', or 'Retest Required'
        // In a real system, there would be MedicalTestWorkRequests or specific statuses to filter by.
        
        // Populate Donors
        for (Network net : system.getNetworkList()) {
            for (Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                    if (org instanceof DonorOrganization) {
                        DonorOrganization donorOrg = (DonorOrganization) org;
                        for (Donor donor : donorOrg.getDonorDirectory().getDonorList()) {
                            // Only show if they need tests or retest
                            if (donor.getStatus().equalsIgnoreCase("Approved by Hospital") || donor.getStatus().equalsIgnoreCase("Retest Required")) {
                                Object[] row = new Object[5];
                                row[0] = donor; // toString of Donor
                                row[1] = "Donor";
                                row[2] = donor.getOrganToDonate();
                                row[3] = donor.getBloodType();
                                row[4] = donor.getStatus();
                                model.addRow(row);
                            }
                        }
                    }
                    else if (org instanceof RecipientOrganization) {
                        RecipientOrganization recipientOrg = (RecipientOrganization) org;
                        for (Recipient recipient : recipientOrg.getRecipientDirectory().getRecipientList()) {
                            // Only show if they need tests or retest
                            if (recipient.getStatus().equalsIgnoreCase("Initial Match Search Performed") || recipient.getStatus().equalsIgnoreCase("Retest Required")) {
                                Object[] row = new Object[5];
                                row[0] = recipient; // toString of Recipient
                                row[1] = "Recipient";
                                row[2] = recipient.getOrganNeeded();
                                row[3] = recipient.getBloodType();
                                row[4] = recipient.getStatus();
                                model.addRow(row);
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        lblEnterpriseValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubjects = new javax.swing.JTable();
        btnUploadResults = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Lab Technician Work Area");

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnterprise.setText("Enterprise:");

        lblEnterpriseValue.setText("<value>");

        tblSubjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Type", "Organ", "Blood Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSubjects);

        btnUploadResults.setText("Upload Test Results");
        btnUploadResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadResultsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Subjects Requiring Tests:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblEnterprise)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblEnterpriseValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnUploadResults, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterprise)
                    .addComponent(lblEnterpriseValue))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUploadResults)
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void btnUploadResultsActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int selectedRow = tblSubjects.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Donor or Recipient.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Object selectedSubject = tblSubjects.getValueAt(selectedRow, 0); // Can be Donor or Recipient

        String testName = JOptionPane.showInputDialog(this, "Enter Test Name:");
        if (testName == null || testName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Test Name cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String resultDetails = JOptionPane.showInputDialog(this, "Enter Result Details:");
        if (resultDetails == null || resultDetails.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Result Details cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Simplified file path for now
        // String filePath = JOptionPane.showInputDialog(this, "Enter File Path (optional):");

        MedicalTestResult newResult = null;
        if (selectedSubject instanceof Donor) {
            newResult = new MedicalTestResult(testName, (Donor) selectedSubject, null);
        } else if (selectedSubject instanceof Recipient) {
            newResult = new MedicalTestResult(testName, null, (Recipient) selectedSubject);
        } else {
             JOptionPane.showMessageDialog(this, "Invalid subject type selected.", "Error", JOptionPane.ERROR_MESSAGE);
             return;
        }
        
        newResult.setResultDetails(resultDetails);
        newResult.setTestDate(new Date());
        newResult.setIsVerified(false);
        newResult.setVerifiedBy(userAccount); // Lab Tech user account

        // Add the MedicalTestResult to the Donor/Recipient
        // This requires Donor/Recipient to have a list of MedicalTestResults
        if (selectedSubject instanceof Donor) {
            Donor donor = (Donor) selectedSubject;
            if (donor.getMedicalTestResultList() == null) {
                donor.setMedicalTestResultList(new ArrayList<MedicalTestResult>());
            }
            donor.getMedicalTestResultList().add(newResult);
            donor.setStatus("Tests Uploaded, Pending Doctor Verification");
        } else if (selectedSubject instanceof Recipient) {
            Recipient recipient = (Recipient) selectedSubject;
             if (recipient.getMedicalTestResultList() == null) {
                recipient.setMedicalTestResultList(new ArrayList<MedicalTestResult>());
            }
            recipient.getMedicalTestResultList().add(newResult);
            recipient.setStatus("Tests Uploaded, Pending Doctor Verification");
        }
        
        JOptionPane.showMessageDialog(this, "Test results uploaded successfully. Status updated.", "Upload Success", JOptionPane.INFORMATION_MESSAGE);
        populateSubjectsTable(); // Refresh table
    }                                                


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnUploadResults;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblEnterpriseValue;
    private javax.swing.JTable tblSubjects;
    // End of variables declaration                   
}
