/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.RecipientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.RecipientOrganization;
import Business.Recipient.Recipient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eric
 */

public class RecipientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RecipientWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private RecipientOrganization recipientOrganization;
    private Enterprise enterprise;
    private Network network;
    private EcoSystem business;
    
    public RecipientWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,
            RecipientOrganization organization, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.recipientOrganization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.business = business;
        
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblMyRegistrations.getModel();
        model.setRowCount(0); // Clear existing rows
        
        // Load all recipients from the organization's directory
        for (Recipient recipient : recipientOrganization.getRecipientDirectory().getRecipientList()) {
            Object[] row = new Object[6];
            row[0] = recipient.getRecipientId();
            row[1] = recipient.getName();
            row[2] = recipient.getOrganNeeded();
            row[3] = recipient.getBloodType();
            row[4] = recipient.getUrgencyLevel();
            row[5] = recipient.getStatus();
            model.addRow(row);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNewRegistration = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMyRegistrations = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Recipient Work Area");
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.insets = new java.awt.Insets(10, 10, 20, 10);
        add(jLabel1, gbc);

        tblMyRegistrations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Organ Needed", "Blood Type", "Urgency", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMyRegistrations);
        
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.fill = java.awt.GridBagConstraints.BOTH;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        add(jScrollPane1, gbc);

        JPanel buttonPanel = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));
        btnNewRegistration.setText("New Registration");
        btnNewRegistration.setBackground(new java.awt.Color(0, 120, 102));
        btnNewRegistration.setForeground(java.awt.Color.WHITE);
        btnNewRegistration.addActionListener(this::btnNewRegistrationActionPerformed);
        buttonPanel.add(btnNewRegistration);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);
        buttonPanel.add(btnRefresh);
        
        gbc.gridy = 2;
        gbc.weighty = 0;
        add(buttonPanel, gbc);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRegistrationActionPerformed
        // TODO add your handling code here:
        // Navigate to registration form - pass 'this' so it can refresh the table on return
        RecipientRegistrationJPanel panel = new RecipientRegistrationJPanel(
                userProcessContainer, userAccount, recipientOrganization, enterprise, this);
        userProcessContainer.add("RecipientRegistrationJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnNewRegistrationActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
        
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewRegistration;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMyRegistrations;
    // End of variables declaration//GEN-END:variables
}
