/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.HospitalRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.DonorRole.DonorRegistrationJPanel;

/**
 *
 * @author wanyuchiu
 */
public class HospitalRoleWorkAreaJPanel extends javax.swing.JPanel {
   
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    /**
     * Creates new form HospitalRoleWorkAreaJPanel
     */
    public HospitalRoleWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization org, Enterprise ent) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = org;
        this.enterprise = ent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewDonorAplication = new javax.swing.JButton();

        btnViewDonorAplication.setText("VIew Donor Application");
        btnViewDonorAplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDonorAplicationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnViewDonorAplication, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(599, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnViewDonorAplication, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(480, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDonorAplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDonorAplicationActionPerformed
        // TODO add your handling code here:
        
        ReviewDonorApplicationJPanel ReviewDonorApplicationJPanel = new ReviewDonorApplicationJPanel(
        userProcessContainer,
        userAccount,
        organization,
        enterprise
    );
    
    userProcessContainer.add("ReviewDonorApplication", ReviewDonorApplicationJPanel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    
    }//GEN-LAST:event_btnViewDonorAplicationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewDonorAplication;
    // End of variables declaration//GEN-END:variables
}
