/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.HospitalRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.DonorRole.DonorRegistrationJPanel;

/**
 *
 * @author wanyuchiu
 */
public class HospitalRoleWorkAreaJPanel extends javax.swing.JPanel {
   
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    /**
     * Creates new form HospitalRoleWorkAreaJPanel
     */
    public HospitalRoleWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization org, Enterprise ent) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = org;
        this.enterprise = ent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewDonorAplication = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        btnViewDonorAplication.setBackground(new java.awt.Color(0, 120, 102));
        btnViewDonorAplication.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewDonorAplication.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDonorAplication.setText("View Donor Application");
        btnViewDonorAplication.setPreferredSize(new java.awt.Dimension(220, 40));
        btnViewDonorAplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDonorAplicationActionPerformed(evt);
            }
        });
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.insets = new java.awt.Insets(20, 0, 0, 0);
        add(btnViewDonorAplication, gbc);

        javax.swing.JLabel titleLabel = new javax.swing.JLabel("Hospital Work Area");
        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 102, 102));
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new java.awt.Insets(0, 0, 0, 0);
        add(titleLabel, gbc);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDonorAplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDonorAplicationActionPerformed
        // TODO add your handling code here:
        
        ReviewDonorApplicationJPanel ReviewDonorApplicationJPanel = new ReviewDonorApplicationJPanel(
        userProcessContainer,
        userAccount,
        organization,
        enterprise
    );
    
    userProcessContainer.add("ReviewDonorApplication", ReviewDonorApplicationJPanel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    
    }//GEN-LAST:event_btnViewDonorAplicationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewDonorAplication;
    // End of variables declaration//GEN-END:variables
}
