/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.HospitalRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonorRegistrationRequest;
import Business.WorkQueue.WorkQueue;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wanyuchiu
 */
public class ReviewDonorApplicationJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    /**
     * Creates new form DonorReviewJPanel
     */
    public ReviewDonorApplicationJPanel(JPanel userProcessContainer, UserAccount account, Organization org, Enterprise ent) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = org;
        this.enterprise = ent;
        
        populateTable();
    }
    /**
     * 填充表格 - 显示所有待审核的 Donor 申请
     */
    private void populateTable() {
        
        // ============ 调试信息 ============
    System.out.println("=== HOSPITAL OFFICER DEBUG ===");
    System.out.println("Hospital Organization: " + organization.getName());
    System.out.println("Organization ID: " + organization.getOrganizationID());
    System.out.println("WorkQueue Size: " + organization.getWorkQueue().getWorkRequestList().size());
    System.out.println("All Requests in WorkQueue:");
    for (int i = 0; i < organization.getWorkQueue().getWorkRequestList().size(); i++) {
        System.out.println("  - Request " + i + ": " + organization.getWorkQueue().getWorkRequestList().get(i).getClass().getName());
        if (organization.getWorkQueue().getWorkRequestList().get(i) instanceof DonorRegistrationRequest) {
            DonorRegistrationRequest req = (DonorRegistrationRequest) organization.getWorkQueue().getWorkRequestList().get(i);
            System.out.println("    ID: " + req.getRequestID() + ", Status: " + req.getStatus());
        }
    }
    System.out.println("==============================");
    // ============ End ============
    
    DefaultTableModel model = (DefaultTableModel) tblReviewDonor.getModel();
    model.setRowCount(0);
    
    // ============ 修改：从 Enterprise 中找到 Donor Organization ============
    WorkQueue workQueue = null;
    
    // 遍历 Enterprise 中的所有 Organization，找到 Donor Organization
    for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
        if (org.getName().equals("Donor Organization")) {
            workQueue = org.getWorkQueue();
            System.out.println("Found Donor Organization! ID: " + org.getOrganizationID());
            System.out.println("WorkQueue Size: " + workQueue.getWorkRequestList().size());
            break;
        }
    }
    
    // 如果没找到 Donor Organization，显示错误
    if (workQueue == null) {
        JOptionPane.showMessageDialog(this, 
            "Error: Cannot find Donor Organization in this Enterprise!", 
            "Configuration Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    // ============ End 修改 ============
    
    // 现在使用找到的 workQueue
    for (int i = 0; i < workQueue.getWorkRequestList().size(); i++) {
        if (workQueue.getWorkRequestList().get(i) instanceof DonorRegistrationRequest) {
            DonorRegistrationRequest request = (DonorRegistrationRequest) workQueue.getWorkRequestList().get(i);
            
            if ("Pending Hospital Review".equals(request.getStatus())) {
                Object[] row = new Object[5];
                row[0] = request.getRequestID();
                row[1] = request.getDonorName();
                row[2] = request.getBloodType();
                row[3] = request.getOrganType();
                row[4] = request.getStatus();
                
                model.addRow(row);
            }
        }
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReviewDonor = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnViewDetail = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setText("Review Donor Aplication:");

        tblReviewDonor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "BloodType", "OrganType", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblReviewDonor);

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnViewDetail.setText("View Detail");
        btnViewDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnViewDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
          int selectedRow = tblReviewDonor.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, 
                "Please select a donor application to approve.", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 获取选中的 Request ID
        String requestID = tblReviewDonor.getValueAt(selectedRow, 0).toString();
        String donorName = tblReviewDonor.getValueAt(selectedRow, 1).toString();
        
        // 确认操作
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to approve the application for: " + donorName + "?", 
            "Confirm Approval", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        // 请求输入审核意见（可选）
        String comments = JOptionPane.showInputDialog(this, 
            "Enter approval comments (optional):", 
            "Approval Comments", 
            JOptionPane.QUESTION_MESSAGE);
        
        // 找到对应的 Request
        DonorRegistrationRequest selectedRequest = findRequestByID(requestID);
        
        if (selectedRequest != null) {
            // 更新 Request 状态
            selectedRequest.setStatus("Approved by Hospital");
            selectedRequest.setResolveDate(new Date());
            selectedRequest.setResolver(userAccount);
            selectedRequest.setReviewComments(comments);
            
            // 同时更新 Donor 对象的状态
            if (selectedRequest.getDonor() != null) {
                selectedRequest.getDonor().setStatus("Approved by Hospital");
            }
            
            JOptionPane.showMessageDialog(this, 
                "✅ Donor application for " + donorName + " has been approved successfully!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // 刷新表格
            populateTable();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Request not found!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
                                              
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
       int selectedRow = tblReviewDonor.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, 
                "Please select a donor application to reject.", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 获取选中的 Request ID
        String requestID = tblReviewDonor.getValueAt(selectedRow, 0).toString();
        String donorName = tblReviewDonor.getValueAt(selectedRow, 1).toString();
        
        // 请求输入拒绝原因（必填）
        String reason = JOptionPane.showInputDialog(this, 
            "Enter rejection reason (required):", 
            "Rejection Reason", 
            JOptionPane.QUESTION_MESSAGE);
        
        if (reason == null || reason.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Rejection reason is required!", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 确认操作
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to reject the application for: " + donorName + "?", 
            "Confirm Rejection", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        // 找到对应的 Request
        DonorRegistrationRequest selectedRequest = findRequestByID(requestID);
        
        if (selectedRequest != null) {
            // 更新 Request 状态
            selectedRequest.setStatus("Rejected by Hospital");
            selectedRequest.setResolveDate(new Date());
            selectedRequest.setResolver(userAccount);
            selectedRequest.setReviewComments(reason);
            
            // 同时更新 Donor 对象的状态
            if (selectedRequest.getDonor() != null) {
                selectedRequest.getDonor().setStatus("Rejected by Hospital");
            }
            
            JOptionPane.showMessageDialog(this, 
                "❌ Donor application for " + donorName + " has been rejected.", 
                "Rejected", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // 刷新表格
            populateTable();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Request not found!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnViewDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblReviewDonor.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, 
                "Please select a donor application to view details.", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 获取选中的 Request ID
        String requestID = tblReviewDonor.getValueAt(selectedRow, 0).toString();
        
        // 找到对应的 Request
        DonorRegistrationRequest selectedRequest = findRequestByID(requestID);
        
        if (selectedRequest == null) {
            JOptionPane.showMessageDialog(this, 
                "Request not found!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 显示详细信息
        String details = String.format(
            "Donor Application Details:\n\n" +
            "Request ID: %s\n" +
            "Donor Name: %s\n" +
            "Age: %d\n" +
            "Blood Type: %s\n" +
            "Organ Type: %s\n" +
            "Contact: %s\n" +
            "Medical History:\n%s\n" +
            "Request Date: %s\n" +
            "Status: %s",
            selectedRequest.getRequestID(),
            selectedRequest.getDonorName(),
            selectedRequest.getAge(),
            selectedRequest.getBloodType(),
            selectedRequest.getOrganType(),
            selectedRequest.getContact(),
            selectedRequest.getMedicalHistory(),
            selectedRequest.getRequestDate(),
            selectedRequest.getStatus()
        );
        
        JOptionPane.showMessageDialog(this, 
            details, 
            "Donor Application Details", 
            JOptionPane.INFORMATION_MESSAGE);
   
                                             

    }//GEN-LAST:event_btnViewDetailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
                                               
    }//GEN-LAST:event_btnBackActionPerformed
 /**
     * 辅助方法：根据 Request ID 查找 DonorRegistrationRequest
     */
    private DonorRegistrationRequest findRequestByID(String requestID) {
        // ============ 修改：从 Donor Organization 查找 ============
    WorkQueue workQueue = null;
    
    // 遍历 Enterprise 中的所有 Organization，找到 Donor Organization
    for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
        if (org.getName().equals("Donor Organization")) {
            workQueue = org.getWorkQueue();
            break;
        }
    }
    
    if (workQueue == null) {
        return null;
    }
    // ============ End 修改 ============
    
    for (int i = 0; i < workQueue.getWorkRequestList().size(); i++) {
        if (workQueue.getWorkRequestList().get(i) instanceof DonorRegistrationRequest) {
            DonorRegistrationRequest request = (DonorRegistrationRequest) workQueue.getWorkRequestList().get(i);
            if (request.getRequestID().equals(requestID)) {
                return request;
            }
        }
     }
       return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnViewDetail;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblReviewDonor;
    // End of variables declaration//GEN-END:variables
}
