package userinterface.TransplantCoordinatorWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

public class TransplantCoordinatorWorkAreaJPanel extends JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private Network network;

    /**
     * Creates new form TransplantCoordinatorWorkAreaJPanel
     */
    public TransplantCoordinatorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        
        lblValue.setText(enterprise.getName()); // Display enterprise name
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblEnterprise = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnManageRecipientRequests = new javax.swing.JButton();
        btnManageLogisticsRequests = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Transplant Coordinator Work Area");
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.insets = new java.awt.Insets(10, 10, 20, 10);
        add(jLabel1, gbc);

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnterprise.setText("Enterprise:");
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        add(lblEnterprise, gbc);

        lblValue.setText("<value>");
        gbc.gridx = 1;
        add(lblValue, gbc);

        btnManageRecipientRequests.setText("Manage Recipient & Matches");
        btnManageRecipientRequests.setBackground(new java.awt.Color(0, 120, 102));
        btnManageRecipientRequests.setForeground(java.awt.Color.WHITE);
        btnManageRecipientRequests.setPreferredSize(new java.awt.Dimension(250, 40));
        btnManageRecipientRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRecipientRequestsActionPerformed(evt);
            }
        });
        gbc.gridy = 2;
        gbc.gridx = 0;
        gbc.gridwidth = 2;
        gbc.insets = new java.awt.Insets(20, 10, 10, 10);
        add(btnManageRecipientRequests, gbc);

        btnManageLogisticsRequests.setText("Manage Organ Transport Requests");
        btnManageLogisticsRequests.setBackground(new java.awt.Color(0, 120, 102));
        btnManageLogisticsRequests.setForeground(java.awt.Color.WHITE);
        btnManageLogisticsRequests.setPreferredSize(new java.awt.Dimension(250, 40));
        btnManageLogisticsRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLogisticsRequestsActionPerformed(evt);
            }
        });
        gbc.gridy = 3;
        gbc.insets = new java.awt.Insets(10, 10, 10, 10);
        add(btnManageLogisticsRequests, gbc);
    }// </editor-fold>                        

    private void btnManageRecipientRequestsActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // Navigate to TransplantCoordinatorRecipientReviewJPanel
        TransplantCoordinatorRecipientReviewJPanel recipientReviewJPanel = new TransplantCoordinatorRecipientReviewJPanel(userProcessContainer, userAccount, organization, enterprise, network, system);
        userProcessContainer.add("TransplantCoordinatorRecipientReviewJPanel", recipientReviewJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }                                                          

    private void btnManageLogisticsRequestsActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // Navigate to TransplantCoordinatorLogisticsRequestJPanel
        TransplantCoordinatorLogisticsRequestJPanel logisticsRequestJPanel = new TransplantCoordinatorLogisticsRequestJPanel(userProcessContainer, userAccount, organization, enterprise, network, system);
        userProcessContainer.add("TransplantCoordinatorLogisticsRequestJPanel", logisticsRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }                                                          


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnManageLogisticsRequests;
    private javax.swing.JButton btnManageRecipientRequests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblValue;
    // End of variables declaration                   
}
