package userinterface.TransplantCoordinatorWorkArea;

import Business.Donor.Donor;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Recipient.Recipient;
import Business.UserAccount.UserAccount;
import Business.Util.MatchingService;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class TransplantCoordinatorRecipientReviewJPanel extends JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private Network network;

    /**
     * Creates new form TransplantCoordinatorRecipientReviewJPanel
     */
    public TransplantCoordinatorRecipientReviewJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        
        populateRecipientTable();
    }

    private void populateRecipientTable() {
        DefaultTableModel model = (DefaultTableModel) recipientJTable.getModel();
        model.setRowCount(0);

        int recipientCount = 0;
        // Assuming organization is TransplantCoordinatorOrganization,
        // it needs to access RecipientOrganization's RecipientDirectory
        // This is a placeholder logic. Real implementation might involve traversing EcoSystem or a shared RecipientDirectory
        // For simplicity, let's assume we can get recipients from the system level or a specific RecipientOrganization
        
        // This part needs refinement based on how Recipients are truly managed and made accessible to TC
        // Currently, it iterates through all networks/enterprises to find RecipientOrganizations and their recipients
        for (Network net : system.getNetworkList()) {
            for (Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                    if (org instanceof Business.Organization.RecipientOrganization) {
                        Business.Organization.RecipientOrganization recipientOrg = (Business.Organization.RecipientOrganization) org;
                        for (Recipient recipient : recipientOrg.getRecipientDirectory().getRecipientList()) {
                            Object[] row = new Object[5];
                            row[0] = recipient; // toString of Recipient should return name
                            row[1] = recipient.getOrganNeeded();
                            row[2] = recipient.getBloodType();
                            row[3] = recipient.getUrgencyLevel();
                            row[4] = recipient.getStatus();
                            model.addRow(row);
                            recipientCount++;
                        }
                    }
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        recipientJTable = new javax.swing.JTable();
        btnFindMatches = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        compatibleDonorsJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCompatibleDonors = new javax.swing.JLabel();

        recipientJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Recipient Name", "Organ Needed", "Blood Type", "Urgency", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(recipientJTable);

        btnFindMatches.setText("Find Initial Matches");
        btnFindMatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindMatchesActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        compatibleDonorsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Donor Name", "Organ To Donate", "Blood Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(compatibleDonorsJTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Recipient Requests & Matches");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Recipient List:");

        lblCompatibleDonors.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCompatibleDonors.setText("Compatible Donors:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCompatibleDonors)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(btnFindMatches, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBack)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFindMatches)
                .addGap(28, 28, 28)
                .addComponent(lblCompatibleDonors)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void btnFindMatchesActionPerformed(java.awt.event.ActionEvent evt) {                                               
        int selectedRow = recipientJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Recipient from the table.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Recipient selectedRecipient = (Recipient) recipientJTable.getValueAt(selectedRow, 0);

        MatchingService matchingService = new MatchingService();
        List<Donor> compatibleDonors = matchingService.findCompatibleDonors(system, selectedRecipient);
        
        populateCompatibleDonorsTable(compatibleDonors);
        
        if (compatibleDonors.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No compatible donors found for " + selectedRecipient.getName() + ".", "No Matches", JOptionPane.INFORMATION_MESSAGE);
            selectedRecipient.setStatus("No Matches Found");
        } else {
            JOptionPane.showMessageDialog(this, compatibleDonors.size() + " compatible donor(s) found for " + selectedRecipient.getName() + ".", "Matches Found", JOptionPane.INFORMATION_MESSAGE);
            selectedRecipient.setStatus("Initial Match Search Performed"); // Or "Matches Found"
        }
        
        // Refresh the recipient table to reflect status change
        populateRecipientTable();
    }                                              

    private void populateCompatibleDonorsTable(List<Donor> compatibleDonors) {
        DefaultTableModel model = (DefaultTableModel) compatibleDonorsJTable.getModel();
        model.setRowCount(0);

        for (Donor donor : compatibleDonors) {
            Object[] row = new Object[4];
            row[0] = donor; // toString of Donor should return name
            row[1] = donor.getOrganToDonate();
            row[2] = donor.getBloodType();
            row[3] = donor.getStatus();
            model.addRow(row);
        }
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {                                        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }                                       


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFindMatches;
    private javax.swing.JTable compatibleDonorsJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCompatibleDonors;
    private javax.swing.JTable recipientJTable;
    // End of variables declaration                   
}
