package userinterface.TransplantCoordinatorWorkArea;

import Business.Donor.Donor;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.LogisticsOrganization;
import Business.Organization.Organization;
import Business.Recipient.Recipient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrganTransportRequest;
import Business.WorkQueue.MedicalTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.List; // To be used if populating table with confirmed matches
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class TransplantCoordinatorLogisticsRequestJPanel extends JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private Network network;

    /**
     * Creates new form TransplantCoordinatorLogisticsRequestJPanel
     */
    public TransplantCoordinatorLogisticsRequestJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        
        populateConfirmedMatchesTable();
    }

    private void populateConfirmedMatchesTable() {
        DefaultTableModel model = (DefaultTableModel) tblConfirmedMatches.getModel();
        model.setRowCount(0);

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof MedicalTestWorkRequest) {
                MedicalTestWorkRequest mRequest = (MedicalTestWorkRequest) request;
                if (mRequest.getStatus().equalsIgnoreCase("Verified, Ready for Transport Coordination")) {
                    Object[] row = new Object[6];
                    row[0] = mRequest.getDonor(); // Donor object
                    row[1] = mRequest.getRecipient(); // Recipient object
                    row[2] = mRequest.getDonor().getOrganToDonate(); // Organ
                    row[3] = mRequest.getDonor().getBloodType(); // Blood Type (assuming same for recipient for a match)
                    row[4] = mRequest.getStatus(); // Test Status
                    row[5] = mRequest; // The request object itself
                    model.addRow(row);
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblConfirmedMatches = new javax.swing.JTable();
        btnRequestTransport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        tblConfirmedMatches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Donor Name", "Recipient Name", "Organ", "Blood Type", "Test Status", "Request"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblConfirmedMatches);

        btnRequestTransport.setText("Request Organ Transport");
        btnRequestTransport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestTransportActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Organ Transport Requests");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Confirmed Matches (Ready for Transport):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(btnRequestTransport)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBack)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnRequestTransport)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void btnRequestTransportActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        int selectedRow = tblConfirmedMatches.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a confirmed match from the table.", "Selection Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        MedicalTestWorkRequest selectedMedicalTestRequest = (MedicalTestWorkRequest) tblConfirmedMatches.getValueAt(selectedRow, 5); // Assuming request object is at index 5

        if (selectedMedicalTestRequest == null) {
            JOptionPane.showMessageDialog(this, "Selected row does not contain a valid Medical Test Request.", "Data Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (selectedMedicalTestRequest.getStatus().equalsIgnoreCase("Organ Transport Requested")) {
            JOptionPane.showMessageDialog(this, "Organ transport has already been requested for this match.", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Donor selectedDonor = selectedMedicalTestRequest.getDonor();
        Recipient selectedRecipient = selectedMedicalTestRequest.getRecipient();

        if (selectedDonor == null || selectedRecipient == null) {
            JOptionPane.showMessageDialog(this, "Medical Test Request does not contain valid Donor/Recipient data.", "Data Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get transport details from a form/dialog
        String pickupLocation = JOptionPane.showInputDialog(this, "Enter Pickup Location (Donor Hospital):");
        if (pickupLocation == null || pickupLocation.trim().isEmpty()) { return; }
        String deliveryLocation = JOptionPane.showInputDialog(this, "Enter Delivery Location (Recipient Hospital):");
        if (deliveryLocation == null || deliveryLocation.trim().isEmpty()) { return; }
        String urgency = (String) JOptionPane.showInputDialog(this, "Select Urgency Level:", "Urgency",
                            JOptionPane.QUESTION_MESSAGE, null, new String[]{"High", "Medium", "Low"}, "Medium");
        if (urgency == null || urgency.trim().isEmpty()) { return; }

        OrganTransportRequest organTransportRequest = new OrganTransportRequest(selectedDonor, selectedRecipient, pickupLocation, deliveryLocation, urgency);
        organTransportRequest.setSender(userAccount);
        organTransportRequest.setRequestDate(new java.util.Date());
        organTransportRequest.setStatus("Pending Logistics Assignment");


        LogisticsOrganization logisticsOrganization = null;
        // Find the Logistics Organization to add the request to
        for (Network net : system.getNetworkList()) {
            for (Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                    if (org instanceof LogisticsOrganization) {
                        logisticsOrganization = (LogisticsOrganization) org;
                        break; 
                    }
                }
                if (logisticsOrganization != null) break;
            }
            if (logisticsOrganization != null) break;
        }

        if (logisticsOrganization != null) {
            logisticsOrganization.getWorkQueue().getWorkRequestList().add(organTransportRequest);
            // userAccount.getWorkQueue().getWorkRequestList().add(organTransportRequest); // Removed: UserAccount does not have a getWorkQueue()

            // Update MedicalTestWorkRequest status
            selectedMedicalTestRequest.setStatus("Organ Transport Requested");
            selectedMedicalTestRequest.setReceiver(logisticsOrganization.getUserAccountDirectory().getUserAccountList().get(0)); // Assign to a logistics user

            // Update Donor and Recipient status
            selectedDonor.setStatus("Organ Transport Requested");
            selectedRecipient.setStatus("Organ Transport Requested");
            
            JOptionPane.showMessageDialog(this, "Organ Transport Request submitted successfully to Logistics. Statuses updated.", "Request Submitted", JOptionPane.INFORMATION_MESSAGE);
            populateConfirmedMatchesTable(); // Refresh table
        } else {
            JOptionPane.showMessageDialog(this, "Could not find a Logistics Organization to send the request to.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                                   

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {                                        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }                                       


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestTransport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblConfirmedMatches;
    // End of variables declaration                   
}
