package userinterface.TransplantCoordinatorWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

public class TransplantCoordinatorWorkAreaJPanel extends JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private Network network;

    /**
     * Creates new form TransplantCoordinatorWorkAreaJPanel
     */
    public TransplantCoordinatorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        
        lblValue.setText(enterprise.getName()); // Display enterprise name
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblEnterprise = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnManageRecipientRequests = new javax.swing.JButton();
        btnManageLogisticsRequests = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnterprise.setText("Enterprise:");

        lblValue.setText("<value>");

        btnManageRecipientRequests.setText("Manage Recipient & Matches");
        btnManageRecipientRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRecipientRequestsActionPerformed(evt);
            }
        });

        btnManageLogisticsRequests.setText("Manage Organ Transport Requests");
        btnManageLogisticsRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLogisticsRequestsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Transplant Coordinator Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageLogisticsRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageRecipientRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEnterprise)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterprise)
                    .addComponent(lblValue))
                .addGap(42, 42, 42)
                .addComponent(btnManageRecipientRequests)
                .addGap(18, 18, 18)
                .addComponent(btnManageLogisticsRequests)
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void btnManageRecipientRequestsActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // Navigate to TransplantCoordinatorRecipientReviewJPanel
        TransplantCoordinatorRecipientReviewJPanel recipientReviewJPanel = new TransplantCoordinatorRecipientReviewJPanel(userProcessContainer, userAccount, organization, enterprise, network, system);
        userProcessContainer.add("TransplantCoordinatorRecipientReviewJPanel", recipientReviewJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }                                                          

    private void btnManageLogisticsRequestsActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // Navigate to TransplantCoordinatorLogisticsRequestJPanel
        TransplantCoordinatorLogisticsRequestJPanel logisticsRequestJPanel = new TransplantCoordinatorLogisticsRequestJPanel(userProcessContainer, userAccount, organization, enterprise, network, system);
        userProcessContainer.add("TransplantCoordinatorLogisticsRequestJPanel", logisticsRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }                                                          


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnManageLogisticsRequests;
    private javax.swing.JButton btnManageRecipientRequests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblValue;
    // End of variables declaration                   
}
